
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-frontiers
owner: ucsb-cs156
repo_name: proj-frontiers
pull_requests: [{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/add-commit-viewing-ui","number":564,"title":"[WIP] Add frontend for viewing commits on specific branch","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/564"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-deleteteamjob","number":563,"title":"Delete team from Github Job","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/563"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-redis","number":562,"title":"Standalone Redis Demonstration","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/562"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-csv-redis","number":561,"title":"Dj csv redis","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/561"},{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-addteammemberjob","number":558,"title":"Add team member job","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/558"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-setTest","number":556,"title":"Test for Using JPA Buddy Generated equals/hashCode","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/556"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-ITFix","number":537,"title":"Adding the Ability to Sign In During End-To-End Tests","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/537"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-frontend-canvas","number":526,"title":"dp - Added settings tab component to the frontend for Canvas credentials [DRAFT]","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/526"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"dj-canvasTeams","number":523,"title":"Adding a Job to Pull Teams from Canvas","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/523"}]
