
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-frontiers
owner: ucsb-cs156
repo_name: proj-frontiers
pull_requests: [{"author":{"id":"U_kgDOBojkhQ","is_bot":false,"login":"DerekKirschbaum","name":""},"headRefName":"dk-teamrepofrontend","number":518,"title":"dk - Added frontend to set off create team repos job","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/518"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"summit-jobname","number":517,"title":"pc - WIP some debugging output to get you started","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/517"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-title","number":514,"title":"dp - new title for course page [DRAFT]","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/514"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-12","number":492,"title":"f25-12","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/492"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-11","number":491,"title":"f25-11","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/491"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-09","number":489,"title":"f25-09","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/489"}]
