
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-frontiers
owner: ucsb-cs156
repo_name: proj-frontiers
pull_requests: [{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-canvas-token-endpoints","number":509,"title":"dp - Added the POST and PUT endpoints for courses with Canvas API tokens.","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/509"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-12","number":492,"title":"f25-12","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/492"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-11","number":491,"title":"f25-11","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/491"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-09","number":489,"title":"f25-09","url":"https://github.com/ucsb-cs156/proj-frontiers/pull/489"}]
